version: "3.4"

services:
  roubank-app:
    image: roubank-app
    container_name: roubank-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:80

  json-server:
    image: roubank-app.json-server
    container_name: json-server
    build:
      context: .
      dockerfile: ./Dockerfile.json-server
    #informa o caminho do db.json no volume compartilhado
    command: --host 0.0.0.0 --port 3000 --watch db.json
    #no azure
    #command: json-server --host 0.0.0.0 --port 3000 --watch https://<nome do seu blob>.blob.core.windows.net/<nome do seu container>/db.json
    ports:
      - 3000:3000
    #compartilhamento de diretorio entre o host e o container
    #volumes:
    #  - ./data:/data
    restart: always
